def csv_escape(value: str) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def build_tracker_csv(candidate_name: str, role_title: str, pipeline_stage: str, review: dict, next_step: str) -> str:
    headers = [
        "Candidate Name",
        "Role",
        "Stage",
        "Review Priority",
        "Match Signals",
        "Missing Items",
        "Job-Term Coverage",
        "Next Human Review Step",
    ]
    row = [
        candidate_name or "N/A",
        role_title,
        pipeline_stage,
        review["priority"],
        "; ".join(review["matched_terms"]),
        "; ".join(review["missing_terms"]),
        f"{review['coverage']}%",
        next_step,
    ]
    return ",".join(headers) + "\n" + ",".join(csv_escape(item) for item in row)


def build_review_packet(candidate_name: str, role_title: str, role_type: str, pipeline_stage: str, job_description: str, resume_text: str, review: dict, questions: list[str], summary: str, subject: str, email: str, next_step: str, responsible_use_note: str) -> str:
    signal_lines = "\n".join(f"- {item}" for item in review["matched_terms"]) or "- No clear match signals found from the provided text."
    missing_lines = "\n".join(f"- {item}" for item in review["missing_terms"]) or "- No major missing terms identified from the provided job description."
    question_lines = "\n".join(f"{index + 1}. {question}" for index, question in enumerate(questions))
    return f"""# RecruitPilot AI Resume Review Packet

## Candidate Tracking
Candidate: {candidate_name or 'N/A'}
Role Title: {role_title}
Role Type: {role_type}
Pipeline Stage: {pipeline_stage}
Review Priority: {review['priority']}
Review Signal Count: {review['signal_count']}
Job-Term Coverage: {review['coverage']}%
Next Human Review Step: {next_step}

## Responsible Use Note
{responsible_use_note}

## Job Description
{job_description or 'No job description provided.'}

## Resume Text Reviewed
{resume_text or 'No resume text provided.'}

## Resume Match Signals
{signal_lines}

## Missing / Unclear Information
{missing_lines}

## Suggested Follow-Up Questions
{question_lines}

## Manager Review Summary
{summary}

## Candidate Follow-Up Email
Subject: {subject}

{email}

---

Generated by RecruitPilot AI.
"""
